
package com.montenegro.fiscal.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FiscalizationServicePortType", targetNamespace = "https://efi.tax.gov.me/fs")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FiscalizationServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns com.montenegro.fiscal.soap.RegisterInvoiceResponse
     */
    @WebMethod(action = "https://efi.tax.gov.me/fs/RegisterInvoice")
    @WebResult(name = "RegisterInvoiceResponse", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "response")
    public RegisterInvoiceResponse registerInvoice(
        @WebParam(name = "RegisterInvoiceRequest", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "request")
        RegisterInvoiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.montenegro.fiscal.soap.RegisterTCRResponse
     */
    @WebMethod(action = "https://efi.tax.gov.me/fs/RegisterTCR")
    @WebResult(name = "RegisterTCRResponse", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "response")
    public RegisterTCRResponse registerTCR(
        @WebParam(name = "RegisterTCRRequest", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "request")
        RegisterTCRRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.montenegro.fiscal.soap.RegisterCashDepositResponse
     */
    @WebMethod(action = "https://efi.tax.gov.me/fs/RegisterCashDeposit")
    @WebResult(name = "RegisterCashDepositResponse", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "response")
    public RegisterCashDepositResponse registerCashDeposit(
        @WebParam(name = "RegisterCashDepositRequest", targetNamespace = "https://efi.tax.gov.me/fs/schema", partName = "request")
        RegisterCashDepositRequest request);

}
