
package com.montenegro.fiscal.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FiscalizationService", targetNamespace = "https://efi.tax.gov.me/fs", wsdlLocation = "classpath:wsdl/fiscal.wsdl")
public class FiscalizationService
    extends Service
{

    private static final URL FISCALIZATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException FISCALIZATIONSERVICE_EXCEPTION;
    private static final QName FISCALIZATIONSERVICE_QNAME = new QName("https://efi.tax.gov.me/fs", "FiscalizationService");

    static {
        FISCALIZATIONSERVICE_WSDL_LOCATION = com.montenegro.fiscal.soap.FiscalizationService.class.getResource("classpath:wsdl/fiscal.wsdl");
        WebServiceException e = null;
        if (FISCALIZATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/fiscal.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FISCALIZATIONSERVICE_EXCEPTION = e;
    }

    public FiscalizationService() {
        super(__getWsdlLocation(), FISCALIZATIONSERVICE_QNAME);
    }

    public FiscalizationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FISCALIZATIONSERVICE_QNAME, features);
    }

    public FiscalizationService(URL wsdlLocation) {
        super(wsdlLocation, FISCALIZATIONSERVICE_QNAME);
    }

    public FiscalizationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FISCALIZATIONSERVICE_QNAME, features);
    }

    public FiscalizationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FiscalizationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FiscalizationServicePortType
     */
    @WebEndpoint(name = "FiscalizationServicePort")
    public FiscalizationServicePortType getFiscalizationServicePort() {
        return super.getPort(new QName("https://efi.tax.gov.me/fs", "FiscalizationServicePort"), FiscalizationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FiscalizationServicePortType
     */
    @WebEndpoint(name = "FiscalizationServicePort")
    public FiscalizationServicePortType getFiscalizationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://efi.tax.gov.me/fs", "FiscalizationServicePort"), FiscalizationServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FISCALIZATIONSERVICE_EXCEPTION!= null) {
            throw FISCALIZATIONSERVICE_EXCEPTION;
        }
        return FISCALIZATIONSERVICE_WSDL_LOCATION;
    }

}
